STRENGTH = [
    'Alchemist',
    'Axe',
    'Bristleback',
    'Centaur Warrunner',
    'Chaos Knight',
    'Dawnbreaker',
    'Doom',
    'Dragon Knight',
    'Earth Spirit',
    'Earthshaker',
    'Elder Titan',
    'Huskar',
    'Kunkka',
    'Legion Commander',
    'Lifestealer',
    'Mars',
    'Night Stalker',
    'Ogre Magi',
    'Omniknight',
    'Primal Beast',
    'Pudge',
    'Slardar',
    'Spirit Breaker',
    'Sven',
    'Tidehunter',
    'Tiny',
    'Treant Protector',
    'Tusk',
    'Underlord',
    'Undying',
    'Wraith King'
]


AGILITY = [
    'Anti-mage',
    'Arc Warden',
    'Bloodseeker',
    'Bounty Hunter',
    'Clinkz',
    'Drow Ranger',
    'Ember Spirit',
    'Faceless Void',
    'Gyrocopter',
    'Hoodwink',
    'Juggernaut',
    'Luna',
    'Medusa',
    'Meepo',
    'Monkey King',
    'Morphling',
    'Naga Siren',
    'Phantom Assassin',
    'Phantom Lancer',
    'Razor',
    'Riki',
    'Shadow Fiend',
    'Slark',
    'Sniper',
    'Spectre',
    'Templar Assassin',
    'Terrorblade',
    'Troll Warlord',
    'Ursa',
    'Viper',
    'Weaver'
]


INTELLIGENCE = [
    'Ancient Apparation',
    'Crystal Maiden',
    'Death Prophet',
    'Disruptor',
    'Enchantress',
    'Grimstroke',
    'Jakiro',
    'Keeper of the Light',
    'Leshrac',
    'Lich',
    'Lina',
    'Lion',
    'Muerta',
    'Nature\'s Prophet',
    'Necrophos',
    'Oracle',
    'Outworld Destroyer',
    'Puck',
    'Pugna',
    'Queen of Pain',
    'Rubick',
    'Shadow Demon',
    'Shadow Shaman',
    'Silencer',
    'Skywrath Mage',
    'Storm Spirit',
    'Tinker',
    'Warlock',
    'Witch Doctor',
    'Zeus'
]


UNIVERSAL = [
    'Abaddon',
    'Bane',
    'Batrider',
    'Beastmaster',
    'Brewmaster',
    'Broodmother',
    'Chen',
    'Clockwerk',
    'Dark Seer',
    'Dark Willow',
    'Dazzle',
    'Engima',
    'Invoker',
    'Io',
    'Lone Druid',
    'Lycan',
    'Magnus',
    'Marci',
    'Mirana',
    'Nyx Assassin',
    'Pangolier',
    'Phoenix',
    'Sand King',
    'Snapfire',
    'Techies',
    'Timbersaw',
    'Vengeful Spirit',
    'Venomancer',
    'Visage',
    'Void Spirit',
    'Windranger',
    'Winter Wyvern'
]
